# search in google as "sonar-project.properties sample" --> Gist
sonar.projectKey=expense_backend
sonar.projectName=Expense Backend
sonar.sources=. # source code is there in current directory that means (.)(dot)
sonar.exclusions=schema, Dockerfile, Jenkinsfile, node_modules